# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: templates
      type: git
      name: DemoSerie/BuildTemplates

trigger: none

variables:
- template: variables.yml@templates


pool:
  name: Hosted VS2017
  demands:
  - npm
  - node.js

steps:
- template: default_steps.yml@templates

- template: template.yml@templates
  parameters:
    buildConfiguration: '${{ variables.BuildConfiguration }}'
    date: '$(date)'



- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: '${{ variables.artifactName }}'