# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables: { BuildConfiguration: release }

pool:
  name: Hosted VS2017
  demands:
  - npm
  - node.js

steps:
- template: template.yml

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'